### ISSUE TITLE
/lootdestroy option

### ISSUE THREAD

**Issue by MetalJacx** [RekkasGit/E3Next#115]
Would be great if we could have a destroy option. If there is also time a command /cleanup that would check your bag for any item you mark with destroy and destroy it for you.

**Comment by Shenlonx** [comment]
Destroying an item is inherently risky with the way the loot structure is in place since items are specified by name and not ID in the loot settings file.  

At this time we have no intention to add destroy functionality to the base e3 install, but this can either be handled under private code on an individual level, or with a standalone macro.
